name: "Homebox"
version: "0.23.1"
slug: "homebox"
description: "Run the Homebox inventory management system as a Home Assistant add-on."
url: "https://github.com/ctf12/homebox-ha-addon"
arch:
  - aarch64
image: "ghcr.io/ctf12/homebox-ha-addon"
startup: services


ingress: true
ingress_port: 7745
ingress_entry: /
panel_icon: mdi:archive
panel_title: Homebox

map:
  - share:rw

