# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Homebox Addon
version: "0.23.1-1"
image: "ghcr.io/ctf12/homebox-ha-addon"
slug: homebox
description: Homebox add-on
url: "https://github.com/ctf12/homebox-ha-addon/"
arch:
  # - armhf
  # - armv7
  - aarch64
  # - amd64
  # - i386
map:
  - share:rw
ports:
  7745/tcp: 7745
